export {default as AdminCreate} from './AdminCreate'
export {default as AdminListLecturer} from './AdminListLecturer'
export {default as AdminListStudents} from './AdminListStudents'
export {default as AdminListCourse} from './AdminListCourse'
export {default as AdminUpdateAccount} from './AdminUpdateAccount'